// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import { HTMLElementRefOf } from "@plasmicapp/react-web"
import * as React from "react"

import {
  DefaultAddingFormProps,
  PlasmicAddingForm
} from "./plasmic/short_stop/PlasmicAddingForm"

export interface AddingFormProps extends DefaultAddingFormProps {
  values?: {
    name: string
    url: string
  }
  handleChange?: (key: any, value: string) => void
  updateLink?: (name: string, url: string) => void
}

function AddingForm_(
  { values, handleChange, updateLink, ...props }: AddingFormProps,
  ref: HTMLElementRefOf<"div">
) {
  function handleConfirm() {
    updateLink && updateLink(values?.name || "", values?.url || "")
  }

  return (
    <PlasmicAddingForm
      onClick={(e) => e.stopPropagation()}
      urlInput={{
        value: values?.url,
        onChange: (e) => {
          handleChange && handleChange("url", e?.target?.value || "")
        },
        onKeyDown: (e) => {
          if (e?.key === "Enter") handleConfirm()
        }
      }}
      linkNameInput={{
        value: values?.name,
        onChange: (e) => {
          handleChange && handleChange("name", e?.target?.value || "")
        },
        onKeyDown: (e) => {
          if (e?.key === "Enter") handleConfirm()
        }
      }}
      button={{
        onClick: handleConfirm
      }}
      root={{ ref }}
      {...props}
    />
  )
}

const AddingForm = React.forwardRef(AddingForm_)
export default AddingForm
