// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import { HTMLElementRefOf } from '@plasmicapp/react-web';
import * as React from 'react';
import { DefaultBlueEditButtonProps, PlasmicBlueEditButton } from './plasmic/short_stop/PlasmicBlueEditButton';

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface BlueEditButtonProps extends Omit<DefaultBlueEditButtonProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultBlueEditButtonProps altogether and have
// total control over the props for your component.
export interface BlueEditButtonProps extends DefaultBlueEditButtonProps {
    handleClickBlueButton: () => void;
}

function BlueEditButton_({ handleClickBlueButton, ...props }: BlueEditButtonProps, ref: HTMLElementRefOf<'div'>) {
    return <PlasmicBlueEditButton onClick={handleClickBlueButton} root={{ ref }} {...props} />;
}

const BlueEditButton = React.forwardRef(BlueEditButton_);
export default BlueEditButton;
