// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import { HTMLElementRefOf } from "@plasmicapp/react-web"
import * as React from "react"

import CustomTooltip from "~/components/CustomTooltip"

import {
  DefaultInfoButtonProps,
  PlasmicInfoButton
} from "./plasmic/short_stop/PlasmicInfoButton"

export interface InfoButtonProps extends DefaultInfoButtonProps {
  tooltipText?: string
}

function InfoButton_(
  { tooltipText, ...props }: InfoButtonProps,
  ref: HTMLElementRefOf<"div">
) {
  if (tooltipText)
    return (
      <CustomTooltip tooltipText={tooltipText} tooltipColor="#222">
        {(tooltipRef) => (
          <PlasmicInfoButton root={{ ref: tooltipRef }} {...props} />
        )}
      </CustomTooltip>
    )
  return <PlasmicInfoButton root={{ ref }} {...props} />
}

const InfoButton = React.forwardRef(InfoButton_)
export default InfoButton
