// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import * as React from "react";
import {
    DefaultLimitAndStopPopupProps,
    PlasmicLimitAndStopPopup
} from "./plasmic/short_stop/PlasmicLimitAndStopPopup";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface LimitAndStopPopupProps extends Omit<DefaultLimitAndStopPopupProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultLimitAndStopPopupProps altogether and have
// total control over the props for your component.
export interface LimitAndStopPopupProps extends DefaultLimitAndStopPopupProps {}

function LimitAndStopPopup_(
  props: LimitAndStopPopupProps,
  ref: HTMLElementRefOf<"div">
) {
  // Use PlasmicLimitAndStopPopup to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicLimitAndStopPopup are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all LimitAndStopPopupProps here, but feel free
  // to do whatever works for you.

  return <PlasmicLimitAndStopPopup root={{ ref }} {...props} />;
}

const LimitAndStopPopup = React.forwardRef(LimitAndStopPopup_);
export default LimitAndStopPopup;
