// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import * as React from 'react';
import { DefaultOptionsProps, PlasmicOptions } from './plasmic/short_stop/PlasmicOptions';

export interface OptionsProps extends DefaultOptionsProps {}

function Options_(props: OptionsProps, ref: HTMLElementRefOf<'div'>) {
    return <PlasmicOptions root={{ ref }} {...props} />;
}

const Options = React.forwardRef(Options_);
export default Options;
