// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import { HTMLElementRefOf } from "@plasmicapp/react-web"
// import { extensionAuth } from 'propro-common-components';
import * as React from "react"
import { AiOutlineLoading } from "react-icons/ai"


import {
  DefaultProProAccountSectionProps,
  PlasmicProProAccountSection
} from "./plasmic/short_stop/PlasmicProProAccountSection"

export interface ProProAccountSectionProps
  extends DefaultProProAccountSectionProps {
  checkingLoginStatus: boolean
  loading: boolean
  error?: string
  handleClickConnectionButton: () => void
}

function ProProAccountSection_(
  {
    checkingLoginStatus,
    handleClickConnectionButton,
    loading,
    error,
    ...props
  }: ProProAccountSectionProps,
  ref: HTMLElementRefOf<"div">
) {
  if (checkingLoginStatus) return

  return (
    <PlasmicProProAccountSection
      root={{ ref }}
      loginButton={{
        onClick: handleClickConnectionButton,
        children: loading ? (
          <AiOutlineLoading className="animate-spin" />
        ) : (
          "Login"
        )
      }}
      errorMessage={error ? <div className="text-red-500">{error}</div> : null}
      {...props}
    />
  )
}

const ProProAccountSection = React.forwardRef(ProProAccountSection_)
export default ProProAccountSection
