// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import { HTMLElementRefOf } from '@plasmicapp/react-web';
import * as React from 'react';
import { DefaultReminderProps, PlasmicReminder } from './plasmic/short_stop/PlasmicReminder';

export interface ReminderProps extends DefaultReminderProps {
    style?: Record<string, string>;
}

function Reminder_({ style, ...props }: ReminderProps, ref: HTMLElementRefOf<'div'>) {
    return <PlasmicReminder root={{ ref, style }} {...props} />;
}

const Reminder = React.forwardRef(Reminder_);
export default Reminder;
