// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import * as React from 'react';
import { DefaultTooltipProps, PlasmicTooltip } from './plasmic/short_stop/PlasmicTooltip';

export interface TooltipProps extends DefaultTooltipProps {}

function Tooltip_(props: TooltipProps, ref: HTMLElementRefOf<'div'>) {
    return <PlasmicTooltip root={{ ref }} {...props} />;
}

const Tooltip = React.forwardRef(Tooltip_);
export default Tooltip;
