[package]
name = "mapmap-test"
version = "0.1.0"
description = "MapMap Test App"
authors = ["propro"]
edition = "2021"

[lib]
name = "mapmap_test_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta.10", features = ["devtools"] }
tauri-plugin-fs = "2.0.0"
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
tauri-plugin-process = "2.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
anyhow = "1.0"
tokio = { version = "1.40", features = ["rt-multi-thread", "macros", "net", "sync"] }
tokio-tungstenite = "0.23"
futures-util = "0.3"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-global-shortcut = "2.0.1"
tauri-plugin-clipboard-manager = "2.2.0"

