export const countdownExhaustedQuotes = [
  '"Just say no" - N. Reagan',
  "Should you?",
  "Maybe not",
  "Are you choosing signal or noise?",
  "Is it more important to make yourself feel a bit better?",
  "Whats more important?",
  "Is this the best time for this?",
  "Really?",
  "Is it worth it?",
  "Was it worth it last time?",
  "This decision might bite you later",
  '"All we have to decide is what to do with the time that is given us" - Gandalf',
  "You don't need more content",
  "What would Jesus do?",
  "What would Chuck Norris do?",
  "What is most likely going to happen?",
  "Just one more…",
  "There are different ways of hitting the pause button",
  "What's really the rebellious thing to do?",
  "What would Arnold do? (hint: pushups)",
  "Second order consequences",
  "We've been here before",
  "Just close some tabs first",
  "Would you do that to a monkey?",
  "We've been here before",
  "Are you never ready?",
  "Hmm",
  "There are better options",
  "Maybe you should complete sth first"
]
